Update prep metrics to add samtools stats in rnaaln
icgc-argo-workflows/argo-modules pull request #41
Opened 2024-07-30 18:42 UTC by guanqiaofeng

In the previous `rnaaln` workflow, the `QC metric` did not include `samtools_stats`. We have decided to add `samtools_stats` to the `QC metric`. The `prep_metrics` module has been updated to handle `samtools_stats` for `rnaaln`.

2024-07-30 18:44 UTC, guanqiaofeng commented on modules/icgc-argo-workflows/prep/metrics/resources/usr/bin/dnaaln.py
> +     'pct_reads_duplicated': 'reads_duplicated_percent',
We handle `percent` as `pct` for standardization. This one was missed. Now correct it to the standard format

2024-07-30 18:46 UTC, guanqiaofeng commented on modules/icgc-argo-workflows/prep/metrics/resources/usr/bin/rnaaln.py
> -        'overall_alignment_rate' : 'overall_alignment_rate'
`overall_alignment_rate` in `hisat2` is duplicated to `pct_reads_mapped` in `samtools_stats`. So removing it

2024-07-30 18:46 UTC, guanqiaofeng commented on modules/icgc-argo-workflows/prep/metrics/resources/usr/bin/rnaaln.py
> +        'unpaired_total' : 'unpaired_total'
`overall_alignment_rate` in `hisat2` is duplicated to `pct_reads_mapped` in `samtools_stats`. So removing it

2024-07-30 18:47 UTC, guanqiaofeng commented on modules/icgc-argo-workflows/prep/metrics/resources/usr/bin/rnaaln.py
> +        'pct_uniquely_mapped' : 'uniquely_mapped_percent',
We handle `percent` as `pct` for standardization. This one was missed. Now correct it to the standard format

2024-07-30 18:48 UTC, guanqiaofeng commented on modules/icgc-argo-workflows/prep/metrics/resources/usr/bin/rnaaln.py
> -        'mismatch_rate' : 'mismatch_rate',
`mismatch_rate` in `star` is duplicated to `mismatch_bases_rate` in `samtools_stats`. So removing it.

2024-07-30 18:49 UTC, guanqiaofeng commented on modules/icgc-argo-workflows/prep/metrics/resources/usr/bin/rnaaln.py
>      }
This section extract the same fields in `samtools_stats` as `dnaaln.py`

2024-08-02 18:48 UTC, lindaxiang approved these changes
LGTM

2024-08-02 19:02 UTC, edsu7 requested changes

2024-08-02 20:22 UTC, guanqiaofeng commented on tests/data/qa/multiqc_data/rnaaln/star/multiqc_sources.txt
> +Picard	RnaSeqMetrics	SA622799	/Users/gfeng/Documents/Work/ICGC-ARGO-WORKFLOWS/rnaaln/compile/nf-core-rnaaln/work/97/cc05f1053a0029a3b30559797f7f62/4/TCRB-CA.DO262498.SA622799.csort.markdup.star.rna_m
Other test files also include personal directory. This file is generated by multiqc step. Maybe we can leave it as it is?

2024-08-06 13:18 UTC, merged