Update workflow names in checkinput
icgc-argo-workflows/argo-modules pull request #45
Opened 2024-09-09 21:07 UTC by guanqiaofeng

update workflow name `DNA Alignment` to `DNA Seq Alignment`, `RNA Alignment` to `RNA Seq Alignment` to make them consistent with other modules

2024-09-10 19:39 UTC, edsu7 requested changes
Minor things, nothing affecting functionality. All tests passed.

2024-09-10 19:39 UTC, edsu7 commented on tests/modules/icgc-argo-workflows/checkinput/nextflow.rnaaln.config
> +    author          = """Linda Xiang"""
```suggestion
    author          = """Guangqiao Feng, Linda Xiang"""
```

2024-09-10 19:39 UTC, edsu7 commented on tests/modules/icgc-argo-workflows/checkinput/nextflow.rnaaln.config
> +    description     = """ICGC-ARGO analysis workflow for DNA alignment"""
```suggestion
    description     = """ICGC-ARGO analysis workflow for RNA alignment"""
```

2024-09-10 19:39 UTC, edsu7 commented on tests/modules/icgc-argo-workflows/checkinput/nextflow.rnaaln.config
> +    homePage        = 'https://github.com/icgc-argo-workflows/dnaaln'
```suggestion
    homePage        = 'https://github.com/icgc-argo-workflows/rnaaln'
```

2024-09-11 14:18 UTC, guanqiaofeng commented on tests/modules/icgc-argo-workflows/checkinput/nextflow.rnaaln.config
> +    description     = """ICGC-ARGO analysis workflow for RNA alignment"""
updated fields to address Edmund's comments

2024-09-13 21:43 UTC, lindaxiang approved these changes
LGTM

2024-09-23 17:07 UTC, merged